version: "3.8"
services:
  db:
    build: ./postgis
    environment:
      POSTGRES_DB: atd_vz_data
      POSTGRES_USER: visionzero
      POSTGRES_PASSWORD: visionzero
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  python:
    build: ./python
    volumes:
      - ./python:/application
    depends_on:
      - db
  adminer:
    build: ./adminer
    ports:
      - 8080:8080
    depends_on:
      - db
  graphql-engine:
    image: hasura/graphql-engine:v2.37.1
    volumes:
      - ./metadata:/metadata
    container_name: visionzero-graphql-engine
    ports:
      - 8084:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://visionzero:visionzero@db:5432/atd_vz_data
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    depends_on:
      - db
    restart: always
volumes:
  db_data:
