COLUMNS = [
    {
        "name": "crash_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": False,
        "is_primary_key": True,
    },
    {
        "name": "onsys_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rr_relat_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "schl_bus_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "toll_road_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "private_dr_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "txdot_rptable_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "thousand_damage_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "road_constr_zone_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "medical_advisory_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "active_school_zone_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "road_constr_zone_wrkr_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "at_intrsct_fl",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "case_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_block_num",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_block_num",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_hwy_num",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_street_desc",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_street_name",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_street_pfx",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_street_sfx",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_street_desc",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_street_name",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_street_pfx",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_street_sfx",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_hwy_num",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_ref_mark_dir",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_ref_mark_dist_uom",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "surf_type_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "crash_date",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "latitude",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "longitude",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_ref_mark_offset_amt",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "crash_speed_limit",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "fhe_collsn_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "light_cond_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "obj_struck_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_rdwy_sys_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_road_part_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_rdwy_sys_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_sec_road_part_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "traffic_cntl_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "wthr_cond_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "intrsct_relat_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "investigat_agency_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "surf_cond_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_city_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "rpt_cris_cnty_id",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "investigator_narrative",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "name": "crash_time",
        "table_name": "crashes",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
    },
    {
        "table_name": "units",
        "editable": False,
        "is_primary_key": True,
        "name": "id",
        "source": "vz",
    },
    {
        "table_name": "units",
        "source": "cris",
        "editable": False,
        "is_primary_key": False,
        "name": "crash_id",
    },
    {
        "table_name": "units",
        "source": "cris",
        "editable": True,
        "is_primary_key": False,
        "name": "unit_nbr",
    },
    {
        "table_name": "persons",
        "editable": False,
        "is_primary_key": True,
        "name": "id",
        "source": "vz",
    },
    {
        "table_name": "persons",
        "editable": False,
        "is_primary_key": False,
        "name": "prsn_nbr",
        "source": "cris",
    },
    {
        "table_name": "persons",
        "editable": False,
        "is_primary_key": False,
        "name": "crash_id",
        "source": "cris",
    },
    {
        "table_name": "persons",
        "editable": True,
        "is_primary_key": False,
        "name": "unit_nbr",
        "source": "cris",
    },
]
